
from django.utils.translation import gettext_lazy as _

languages = [
    ('aa', _('Afar')),
    ('ab', _('Abkhazian')),
    ('ae', _('Avestan')),
    ('af', _('Afrikaans')),
    ('ak', _('Akan')),
    ('am', _('Amharic')),
    ('an', _('Aragonese')),
    ('ar', _('Arabic')),
    ('as', _('Assamese')),
    ('av', _('Avaric')),
    ('ay', _('Aymara')),
    ('az', _('Azerbaijani')),
    ('ba', _('Bashkir')),
    ('be', _('Belarusian')),
    ('bg', _('Bulgarian')),
    ('bh', _('Bihari languages')),
    ('bi', _('Bislama')),
    ('bm', _('Bambara')),
    ('bn', _('Bengali')),
    ('bo', _('Tibetan')),
    ('br', _('Breton')),
    ('bs', _('Bosnian')),
    ('ca', _('Catalan; Valencian')),
    ('ce', _('Chechen')),
    ('ch', _('Chamorro')),
    ('co', _('Corsican')),
    ('cr', _('Cree')),
    ('cs', _('Czech')),
    ('cu', _('Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic')),
    ('cv', _('Chuvash')),
    ('cy', _('Welsh')),
    ('da', _('Danish')),
    ('de', _('German')),
    ('dv', _('Divehi; Dhivehi; Maldivian')),
    ('dz', _('Dzongkha')),
    ('ee', _('Ewe')),
    ('el', _('Greek, Modern (1453-)')),
    ('en', _('English')),
    ('eo', _('Esperanto')),
    ('es', _('Spanish; Castilian')),
    ('et', _('Estonian')),
    ('eu', _('Basque')),
    ('fa', _('Persian')),
    ('ff', _('Fulah')),
    ('fi', _('Finnish')),
    ('fj', _('Fijian')),
    ('fo', _('Faroese')),
    ('fr', _('French')),
    ('fy', _('Western Frisian')),
    ('ga', _('Irish')),
    ('gd', _('Gaelic; Scottish Gaelic')),
    ('gl', _('Galician')),
    ('gn', _('Guarani')),
    ('gu', _('Gujarati')),
    ('gv', _('Manx')),
    ('ha', _('Hausa')),
    ('he', _('Hebrew')),
    ('hi', _('Hindi')),
    ('ho', _('Hiri Motu')),
    ('hr', _('Croatian')),
    ('ht', _('Haitian; Haitian Creole')),
    ('hu', _('Hungarian')),
    ('hy', _('Armenian')),
    ('hz', _('Herero')),
    ('ia', _('Interlingua (International Auxiliary Language Association)')),
    ('id', _('Indonesian')),
    ('ie', _('Interlingue; Occidental')),
    ('ig', _('Igbo')),
    ('ii', _('Sichuan Yi; Nuosu')),
    ('ik', _('Inupiaq')),
    ('io', _('Ido')),
    ('is', _('Icelandic')),
    ('it', _('Italian')),
    ('iu', _('Inuktitut')),
    ('ja', _('Japanese')),
    ('jv', _('Javanese')),
    ('ka', _('Georgian')),
    ('kg', _('Kongo')),
    ('ki', _('Kikuyu; Gikuyu')),
    ('kj', _('Kuanyama; Kwanyama')),
    ('kk', _('Kazakh')),
    ('kl', _('Kalaallisut; Greenlandic')),
    ('km', _('Central Khmer')),
    ('kn', _('Kannada')),
    ('ko', _('Korean')),
    ('kr', _('Kanuri')),
    ('ks', _('Kashmiri')),
    ('ku', _('Kurdish')),
    ('kv', _('Komi')),
    ('kw', _('Cornish')),
    ('ky', _('Kirghiz; Kyrgyz')),
    ('la', _('Latin')),
    ('lb', _('Luxembourgish; Letzeburgesch')),
    ('lg', _('Ganda')),
    ('li', _('Limburgan; Limburger; Limburgish')),
    ('ln', _('Lingala')),
    ('lo', _('Lao')),
    ('lt', _('Lithuanian')),
    ('lu', _('Luba-Katanga')),
    ('lv', _('Latvian')),
    ('mg', _('Malagasy')),
    ('mh', _('Marshallese')),
    ('mi', _('Maori')),
    ('mk', _('Macedonian')),
    ('ml', _('Malayalam')),
    ('mn', _('Mongolian')),
    ('mr', _('Marathi')),
    ('ms', _('Malay')),
    ('mt', _('Maltese')),
    ('my', _('Burmese')),
    ('na', _('Nauru')),
    ('nb', _('Bokmål, Norwegian; Norwegian Bokmål')),
    ('nd', _('Ndebele, North; North Ndebele')),
    ('ne', _('Nepali')),
    ('ng', _('Ndonga')),
    ('nl', _('Dutch; Flemish')),
    ('nn', _('Norwegian Nynorsk; Nynorsk, Norwegian')),
    ('no', _('Norwegian')),
    ('nr', _('Ndebele, South; South Ndebele')),
    ('nv', _('Navajo; Navaho')),
    ('ny', _('Chichewa; Chewa; Nyanja')),
    ('oc', _('Occitan (post 1500)')),
    ('oj', _('Ojibwa')),
    ('om', _('Oromo')),
    ('or', _('Oriya')),
    ('os', _('Ossetian; Ossetic')),
    ('pa', _('Panjabi; Punjabi')),
    ('pi', _('Pali')),
    ('pl', _('Polish')),
    ('ps', _('Pushto; Pashto')),
    ('pt', _('Portuguese')),
    ('qu', _('Quechua')),
    ('rm', _('Romansh')),
    ('rn', _('Rundi')),
    ('ro', _('Romanian; Moldavian; Moldovan')),
    ('ru', _('Russian')),
    ('rw', _('Kinyarwanda')),
    ('sa', _('Sanskrit')),
    ('sc', _('Sardinian')),
    ('sd', _('Sindhi')),
    ('se', _('Northern Sami')),
    ('sg', _('Sango')),
    ('si', _('Sinhala; Sinhalese')),
    ('sk', _('Slovak')),
    ('sl', _('Slovenian')),
    ('sm', _('Samoan')),
    ('sn', _('Shona')),
    ('so', _('Somali')),
    ('sq', _('Albanian')),
    ('sr', _('Serbian')),
    ('ss', _('Swati')),
    ('st', _('Sotho, Southern')),
    ('su', _('Sundanese')),
    ('sv', _('Swedish')),
    ('sw', _('Swahili')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
    ('tg', _('Tajik')),
    ('th', _('Thai')),
    ('ti', _('Tigrinya')),
    ('tk', _('Turkmen')),
    ('tl', _('Tagalog')),
    ('tn', _('Tswana')),
    ('to', _('Tonga (Tonga Islands)')),
    ('tr', _('Turkish')),
    ('ts', _('Tsonga')),
    ('tt', _('Tatar')),
    ('tw', _('Twi')),
    ('ty', _('Tahitian')),
    ('ug', _('Uighur; Uyghur')),
    ('uk', _('Ukrainian')),
    ('ur', _('Urdu')),
    ('uz', _('Uzbek')),
    ('ve', _('Venda')),
    ('vi', _('Vietnamese')),
    ('vo', _('Volapük')),
    ('wa', _('Walloon')),
    ('wo', _('Wolof')),
    ('xh', _('Xhosa')),
    ('yi', _('Yiddish')),
    ('yo', _('Yoruba')),
    ('za', _('Zhuang; Chuang')),
    ('zh', _('Chinese')),
    ('zu', _('Zulu')),
]

country_codes = [
    ('AW', 'Aruba'),
    ('AF', 'Afghanistan'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AX', 'Åland Islands'),
    ('AL', 'Albania'),
    ('AD', 'Andorra'),
    ('AE', 'United Arab Emirates'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AS', 'American Samoa'),
    ('AQ', 'Antarctica'),
    ('TF', 'French Southern Territories'),
    ('AG', 'Antigua and Barbuda'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BI', 'Burundi'),
    ('BE', 'Belgium'),
    ('BJ', 'Benin'),
    ('BQ', 'Bonaire, Sint Eustatius and Saba'),
    ('BF', 'Burkina Faso'),
    ('BD', 'Bangladesh'),
    ('BG', 'Bulgaria'),
    ('BH', 'Bahrain'),
    ('BS', 'Bahamas'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BL', 'Saint Barthélemy'),
    ('BY', 'Belarus'),
    ('BZ', 'Belize'),
    ('BM', 'Bermuda'),
    ('BO', 'Bolivia'),
    ('BR', 'Brazil'),
    ('BB', 'Barbados'),
    ('BN', 'Brunei Darussalam'),
    ('BT', 'Bhutan'),
    ('BV', 'Bouvet Island'),
    ('BW', 'Botswana'),
    ('CF', 'Central African Republic'),
    ('CA', 'Canada'),
    ('CC', 'Cocos (Keeling) Islands'),
    ('CH', 'Switzerland'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CI', "Côte d'Ivoire"),
    ('CM', 'Cameroon'),
    ('CD', 'Congo, Democratic Republic of the'),
    ('CG', 'Congo'),
    ('CK', 'Cook Islands'),
    ('CO', 'Colombia'),
    ('KM', 'Comoros'),
    ('CV', 'Cabo Verde'),
    ('CR', 'Costa Rica'),
    ('CU', 'Cuba'),
    ('CW', 'Curaçao'),
    ('CX', 'Christmas Island'),
    ('KY', 'Cayman Islands'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czechia'),
    ('DE', 'Germany'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DK', 'Denmark'),
    ('DO', 'Dominican Republic'),
    ('DZ', 'Algeria'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('ER', 'Eritrea'),
    ('EH', 'Western Sahara'),
    ('ES', 'Spain'),
    ('EE', 'Estonia'),
    ('ET', 'Ethiopia'),
    ('FI', 'Finland'),
    ('FJ', 'Fiji'),
    ('FK', 'Falkland Islands (Malvinas)'),
    ('FR', 'France'),
    ('FO', 'Faroe Islands'),
    ('FM', 'Micronesia (Federated States of)'),
    ('GA', 'Gabon'),
    ('GB', 'United Kingdom'),
    ('GE', 'Georgia'),
    ('GG', 'Guernsey'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GN', 'Guinea'),
    ('GP', 'Guadeloupe'),
    ('GM', 'Gambia'),
    ('GW', 'Guinea-Bissau'),
    ('GQ', 'Equatorial Guinea'),
    ('GR', 'Greece'),
    ('GD', 'Grenada'),
    ('GL', 'Greenland'),
    ('GT', 'Guatemala'),
    ('GF', 'French Guiana'),
    ('GU', 'Guam'),
    ('GY', 'Guyana'),
    ('HK', 'Hong Kong'),
    ('HM', 'Heard Island and McDonald Islands'),
    ('HN', 'Honduras'),
    ('HR', 'Croatia'),
    ('HT', 'Haiti'),
    ('HU', 'Hungary'),
    ('ID', 'Indonesia'),
    ('IM', 'Isle of Man'),
    ('IN', 'India'),
    ('IO', 'British Indian Ocean Territory'),
    ('IE', 'Ireland'),
    ('IR', 'Iran (Islamic Republic of Iran)'),
    ('IQ', 'Iraq'),
    ('IS', 'Iceland'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JE', 'Jersey'),
    ('JO', 'Jordan'),
    ('JP', 'Japan'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('KG', 'Kyrgyzstan'),
    ('KH', 'Cambodia'),
    ('KI', 'Kiribati'),
    ('KN', 'Saint Kitts and Nevis'),
    ('KR', 'Korea (Republic of)'),
    ('KW', 'Kuwait'),
    ('LA', 'Lao People\'s Democratic Republic'),
    ('LB', 'Lebanon'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LC', 'Saint Lucia'),
    ('LI', 'Liechtenstein'),
    ('LK', 'Sri Lanka'),
    ('LS', 'Lesotho'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('LV', 'Latvia'),
    ('MO', 'Macao'),
    ('MF', 'Saint Martin (French part)'),
    ('MA', 'Morocco'),
    ('MC', 'Monaco'),
    ('MD', 'Moldova (Republic of)'),
    ('MG', 'Madagascar'),
    ('MV', 'Maldives'),
    ('MX', 'Mexico'),
    ('MH', 'Marshall Islands'),
    ('MK', 'North Macedonia'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MM', 'Myanmar'),
    ('ME', 'Montenegro'),
    ('MN', 'Mongolia'),
    ('MP', 'Northern Mariana Islands'),
    ('MZ', 'Mozambique'),
    ('MR', 'Mauritania'),
    ('MS', 'Montserrat'),
    ('MQ', 'Martinique'),
    ('MU', 'Mauritius'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('YT', 'Mayotte'),
    ('NA', 'Namibia'),
    ('NC', 'New Caledonia'),
    ('NE', 'Niger'),
    ('NF', 'Norfolk Island'),
    ('NG', 'Nigeria'),
    ('NI', 'Nicaragua'),
    ('NU', 'Niue'),
    ('NL', 'Netherlands'),
    ('NO', 'Norway'),
    ('NP', 'Nepal'),
    ('NR', 'Nauru'),
    ('NZ', 'New Zealand'),
    ('OM', 'Oman'),
    ('PK', 'Pakistan'),
    ('PA', 'Panama'),
    ('PN', 'Pitcairn'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PW', 'Palau'),
    ('PG', 'Papua New Guinea'),
    ('PL', 'Poland'),
    ('PR', 'Puerto Rico'),
    ('KP', 'Korea (Democratic People\'s Republic of)'),
    ('PT', 'Portugal'),
    ('PY', 'Paraguay'),
    ('PS', 'Palestine, State of'),
    ('PF', 'French Polynesia'),
    ('QA', 'Qatar'),
    ('RE', 'Réunion'),
    ('RO', 'Romania'),
    ('RU', 'Russian Federation'),
    ('RW', 'Rwanda'),
    ('SA', 'Saudi Arabia'),
    ('SD', 'Sudan'),
    ('SN', 'Senegal'),
    ('SG', 'Singapore'),
    ('GS', 'South Georgia and the South Sandwich Islands'),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('SJ', 'Svalbard and Jan Mayen'),
    ('SB', 'Solomon Islands'),
    ('SL', 'Sierra Leone'),
    ('SV', 'El Salvador'),
    ('SM', 'San Marino'),
    ('SO', 'Somalia'),
    ('PM', 'Saint Pierre and Miquelon'),
    ('RS', 'Serbia'),
    ('SS', 'South Sudan'),
    ('ST', 'Sao Tome and Principe'),
    ('SR', 'Suriname'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SE', 'Sweden'),
    ('SZ', 'Eswatini'),
    ('SC', 'Seychelles'),
    ('SY', 'Syrian Arab Republic'),
    ('TC', 'Turks and Caicos Islands'),
    ('TD', 'Chad'),
    ('TG', 'Togo'),
    ('TH', 'Thailand'),
    ('TJ', 'Tajikistan'),
    ('TK', 'Tokelau'),
    ('TM', 'Turkmenistan'),
    ('TL', 'Timor-Leste'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad and Tobago'),
    ('TN', 'Tunisia'),
    ('TR', 'Türkiye'),
    ('TV', 'Tuvalu'),
    ('TW', 'Taiwan'),
    ('TZ', 'Tanzania, United Republic of'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('UM', 'United States Minor Outlying Islands'),
    ('UY', 'Uruguay'),
    ('US', 'United States of America'),
    ('UZ', 'Uzbekistan'),
    ('VA', 'Holy See'),
    ('VC', 'Saint Vincent and the Grenadines'),
    ('VE', 'Venezuela (Bolivarian Republic of)'),
    ('VG', 'Virgin Islands (British)'),
    ('VI', 'Virgin Islands (U.S.)'),
    ('VN', 'Viet Nam'),
    ('VU', 'Vanuatu'),
    ('WF', 'Wallis and Futuna'),
    ('WS', 'Samoa'),
    ('YE', 'Yemen'),
    ('ZA', 'South Africa'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe'),
]

countries = [
    ('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'),
        ('Angola', 'Angola'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'),
        ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'),
        ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'),
        ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bhutan', 'Bhutan'),
        ('Bolivia', 'Bolivia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'),
        ('Brazil', 'Brazil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'),
        ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'),
        ('Cape Verde', 'Cape Verde'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'),
        ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'),
        ('Congo', 'Congo'), ('Congo, Democratic Republic of', 'Congo, Democratic Republic of'),
        ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Cyprus', 'Cyprus'),
        ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'),
        ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('East Timor', 'East Timor'),
        ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'),
        ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'),
        ('Ethiopia', 'Ethiopia'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'),
        ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'),
        ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Greenland', 'Greenland'), ('Guadeloupe', 'Guadeloupe'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'),
        ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'),
        ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'),
        ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Israel', 'Israel'), ('Italy', 'Italy'),
        ('Ivory Coast', 'Ivory Coast'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'),
        ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea, North', 'Korea, North'),
        ('Korea, South', 'Korea, South'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Kyrgyz Republic', 'Kyrgyz Republic'), ('Laos', 'Laos'),
        ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'),
        ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'),
        ('Luxembourg', 'Luxembourg'), ('Macedonia', 'Macedonia'), ('Madagascar', 'Madagascar'),
        ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'),
        ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Mauritania', 'Mauritania'),
        ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Moldova', 'Moldova'),
        ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Morocco', 'Morocco'),
        ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'),
        ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'),
        ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Norway', 'Norway'),
        ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'),
        ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'),
        ('Qatar', 'Qatar'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('Rwanda', 'Rwanda'),
        ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'),
        ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Samoa', 'Samoa'),
        ('San Marino', 'San Marino'), ('Sao Tome and Principe', 'Sao Tome and Principe'),
        ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'),
        ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapore', 'Singapore'),
        ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Solomon Islands', 'Solomon Islands'),
        ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Sudan', 'South Sudan'),
        ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'),
        ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syria', 'Syria'),
        ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'),
        ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'),
        ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Tuvalu', 'Tuvalu'),
        ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'),
        ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Uruguay', 'Uruguay'),
        ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Vatican City', 'Vatican City'),
        ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'),
        ('Zimbabwe', 'Zimbabwe')
]


ethnicities = [
    ('English', 'English'),
    ("Han Chinese", "Han Chinese"),
    ("Arab", "Arab"),
    ("Bengali", "Bengali"),
    ("Hispanic/Latino", "Hispanic/Latino"),
    ("Punjabi", "Punjabi"),
    ("Russian", "Russian"),
    ("Javanese", "Javanese"),
    ("Japanese", "Japanese"),
    ("German", "German"),
    ("Korean", "Korean"),
    ("French", "French"),
    ("Vietnamese", "Vietnamese"),
    ("Telugu", "Telugu"),
    ("Marathi", "Marathi"),
    ("Tamil", "Tamil"),
    ("Turkish", "Turkish"),
    ("Italian", "Italian"),
    ("Yoruba", "Yoruba"),
    ("Gujarati", "Gujarati"),
    ("Persian", "Persian"),
    ("Polish", "Polish"),
    ("Pashto", "Pashto"),
    ("Kannada", "Kannada"),
    ("Xhosa", "Xhosa"),
    ("Malayali", "Malayali"),
    ("Sundanese", "Sundanese"),
    ("Hausa", "Hausa"),
    ("Thai", "Thai"),
    ("Amhara", "Amhara"),
    ("Oromo", "Oromo"),
    ("Burmese", "Burmese"),
    ("Ukrainian", "Ukrainian"),
    ("Bhojpuri", "Bhojpuri"),
    ("Tagalog", "Tagalog"),
    ("Malay", "Malay"),
    ("Igbo", "Igbo"),
    ("Uzbek", "Uzbek"),
    ("Sindhi", "Sindhi"),
    ("Oriya", "Oriya"),
    ("Romanian", "Romanian"),
    ("Cebuano", "Cebuano"),
    ("Dutch", "Dutch"),
    ("Kurdish", "Kurdish"),
    ("Serbo-Croatian", "Serbo-Croatian"),
    ("Malagasy", "Malagasy"),
    ("Saraiki", "Saraiki"),
    ("Nepali", "Nepali"),
    ("Sinhalese", "Sinhalese"),
    ("Khmer", "Khmer"),
    ("Tutsi", "Tutsi"),
    ("Hutu", "Hutu"),
    ("Fulani", "Fulani"),
    ("Somali", "Somali"),
    ("Greek", "Greek"),
    ("Czech", "Czech"),
    ("Portuguese", "Portuguese"),
    ("Swedish", "Swedish"),
    ("Hungarian", "Hungarian"),
    ("Belarusian", "Belarusian"),
    ("Zulu", "Zulu"),
    ("Jewish", "Jewish"),
    ("Armenian", "Armenian"),
    ("Berber", "Berber"),
    ("Kazakh", "Kazakh"),
    ("Tibetan", "Tibetan"),
    ("Uyghur", "Uyghur"),
    ("Hmong", "Hmong"),
    ("Tatar", "Tatar"),
    ("Chechen", "Chechen"),
    ("Romani", "Romani"),
    ("Akan", "Akan"),
    ("Shona", "Shona"),
    ("Maori", "Maori"),
    ("Aboriginal Australian", "Aboriginal Australian"),
    ("Inuit", "Inuit"),
    ("Native American", "Native American"),
    ("Quechua", "Quechua"),
    ("Aymara", "Aymara"),
    ("Guarani", "Guarani"),
]

