# Generated by Django 5.0.6 on 2024-10-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_city_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
