# Generated by Django 5.0.6 on 2024-10-21 20:21

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_is_admin_remove_user_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain alphanumeric characters, underscores, and hyphens.', regex='^[a-zA-Z0-9_-]+$'), api.models.validate_username]),
        ),
    ]
