# Generated by Django 5.0.6 on 2024-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default=12345678, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
