# Generated by Django 5.0.6 on 2024-10-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_title_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
