# Generated by Django 5.0.6 on 2024-10-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_genre_rename_date_playlist_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
