# Generated by Django 5.0.6 on 2024-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
