# Generated by Django 5.0.6 on 2024-10-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_artist_dob_remove_user_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nationality',
            new_name='country',
        ),
    ]
