# Generated by Django 5.1.2 on 2024-10-25 08:28

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'free'), ('premium', 'premium'), ('family', 'family')], default='Free', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', regex='^[a-zA-Z0-9_-]+$'), api.models.validate_username]),
        ),
    ]
